# Generated by Django 3.2.15 on 2023-02-26 19:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('notifications', models.CharField(choices=[('me', 'Me'), ('me-agent', 'Me Agent'), ('agent', 'Agent'), ('disabled', 'Disabled')], default='me', max_length=15)),
                ('turn_calls_to_agent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Користувач'), ('manager', 'Менеджер'), ('admin', 'Адміністратор'), ('builder', 'Забудовник')], max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('common', 'Common'), ('lux', 'Lux')], max_length=25)),
                ('sum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, 'Sum cannot be less than 0.00')])),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateTimeField()),
                ('auto_pay', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('all', 'Всі'), ('secondary-market', 'Вторинний ринок'), ('many-floors', 'Багатоповерхівка'), ('cottage', 'Котедж')], max_length=40)),
                ('house_status', models.CharField(choices=[('rented', 'Здана')], max_length=30)),
                ('district', models.CharField(max_length=200)),
                ('micro_district', models.CharField(max_length=200)),
                ('room_amount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('price_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('square_from', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('square_to', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_option', models.CharField(choices=[('mortgage', 'Іпотека'), ('parent-capital', 'Материнський капітал')], max_length=40)),
                ('housing_condition', models.CharField(choices=[('repair-required', 'Потребує ремонту'), ('good', 'Задовільний')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.role'),
        ),
    ]
