# Generated by Django 3.2.15 on 2023-03-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='users/logo/'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('user', 'Користувач'), ('manager', 'Менеджер'), ('admin', 'Адміністратор'), ('builder', 'Забудовник')], max_length=55, unique=True),
        ),
    ]
