# Generated by Django 3.2.15 on 2023-03-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230303_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='house_type',
            field=models.CharField(choices=[('', 'Всі'), ('secondary-market', 'Вторинний ринок'), ('many-floors', 'Багатоповерхівка'), ('cottage', 'Котедж')], max_length=40),
        ),
    ]
