# Generated by Django 3.2.15 on 2023-03-02 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcomplex',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='status',
            field=models.CharField(choices=[('flats', 'Квартири'), ('cottage', 'Котедж'), ('many-floors', 'Багатоповерхівка'), ('secondary-market', 'Вторинний ринок')], default='flats', max_length=50),
        ),
    ]
