# Generated by Django 3.2.15 on 2023-03-14 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flats', '0005_corps_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboardflat',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chessboardflat',
            name='chessboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flats.chessboard'),
        ),
        migrations.AlterField(
            model_name='chessboardflat',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flats.flat'),
        ),
    ]
