# Generated by Django 3.2.15 on 2023-03-18 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0006_auto_20230314_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='sequence_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
