# Generated by Django 3.2.15 on 2023-03-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0008_remove_chessboard_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessboard',
            name='chess_type',
        ),
    ]
