# Generated by Django 3.2.15 on 2023-03-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0010_chessboard_residential_complex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flats.promotiontype'),
        ),
    ]
