# Generated by Django 3.2.15 on 2023-03-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0011_alter_promotion_promotion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboardflat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-22 13:56:44.480547+02'),
            preserve_default=False,
        ),
    ]
