# Generated by Django 3.2.15 on 2023-03-30 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0015_alter_promotion_chessboard_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessboardflat',
            name='flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flats.flat'),
        ),
    ]
