# Generated by Django 3.2.15 on 2023-03-31 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0016_alter_chessboardflat_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='chessboard_flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flats.chessboardflat'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='residential_complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flats.residentialcomplex'),
        ),
    ]
