# Generated by Django 3.2.15 on 2023-04-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0018_auto_20230401_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessboardflat',
            name='called_off',
            field=models.BooleanField(default=False),
        ),
    ]
